version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: pengaduan_masyarakat_web
    ports:
      - "8083:80"  # Ubah port eksternal ke 8083
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mysql-phpmyadmin

  app:
    container_name: pengaduan_masyarakat_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    networks:
      - mysql-phpmyadmin
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pengaduan_masyarakat_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pengaduan_masyarakat
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data: